### ISSUE TITLE
Error with class constant

### ISSUE THREAD

**Issue by Usmon** [goodoneuz/pay-uz#48]
Hi guys.
Laravel 6.x: 
Symfony\Component\Debug\Exception\FatalThrowableError
Undefined class constant 'CUSTOM_FORM'
![error](https://user-images.githubusercontent.com/10257901/77996230-ad435f00-7346-11ea-9dd3-2217b21c1bc7.JPG)

**Comment by shaxzodbek-uzb** [comment]
Rahmat ko'rib chiqaman


вт, 31 мар. 2020 г. в 11:57, Usmon <notifications@github.com>:

**Comment by shaxzodbek-uzb** [comment]
2.0.1 shu versiyani tekshirib ko'ring

**Comment by Usmon** [comment]
Rahmat katta!

**Comment by shaxzodbek-uzb** [comment]
composerdan aynan shu packageni update qiling
