### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by musobekmadrimov** [goodoneuz/pay-uz#60]
I am facing this error when I run `composer require goodoneuz/pay-uz`

![image](https://github.com/shaxzodbek-uzb/pay-uz/assets/66286036/c010a726-c0a7-4833-bac2-79eb275c34b5)

I am sorry if I was mistaken, I am new.. Thanks!

By the way, I am using Laravel 10.

**Comment by shaxzodbek-uzb** [comment]
thanks, we will fix it, asap

@abdurashid-dev

**Comment by shaxzodbek-uzb** [comment]
Completed

**Comment by shaxzodbek-uzb** [comment]
Completed
